config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :tasks
  resources :tags

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_and_belongs_to_many :tasks
    validates :name, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
    validates :title, presence: true

    enum :status, ready: 1, progress: 2, complate: 3, pend: 4

    has_and_belongs_to_many :tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    def index
        tag = Tag.find_by(id: params[:tag_id])
        if tag
            @tag_name = tag.name
            @tasks = tag.tasks
        end
    end

    def new
        @tags = Tag.all
        @tag = Tag.new
    end

    def create
        @tag = Tag.new
        @tag.attributes = params.require(:tag).permit(:name)
        @tag.save!

        redirect_to tags_path
    rescue ActiveRecord::RecordInvalid
        render action: :new, status: :unprocessable_entity
    end

    def edit
        @tag = Tag.find params[:id]
    end

    def update
        @tag = Tag.find params[:id]
        @tag.attributes = params.require(:tag).permit(:name)
        @tag.save!

        redirect_to tags_path
    rescue ActiveRecord::RecordInvalid
        render action: :new, status: :unprocessable_entity
    end

    def destroy
        @tag = Tag.find params[:id]
        @tag.destroy
        redirect_to tags_path
    end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

    def index
        @tasks = params[:status].nil? ? Task.all : Task.where(status: params[:status])
        @today_tasks = Task.where(end_date: Date.today).where.not(status: "complate")
        @delay_tasks = Task.where(end_date: (..Date.yesterday)).where.not(status: "complate")
        @tags = Tag.all
    end

    def new
        @task = Task.new
    end

    def create
        @task = Task.new
        @task.attributes = params.require(:task).permit(:title, :body, :start_date, :end_date, :status, tag_ids: [])
        @task.save!

        redirect_to task_path(@task)
    rescue ActiveRecord::RecordInvalid
        render action: :new, status: :unprocessable_entity
    end

    def show
        @task = Task.find params[:id]
    end

    def edit
        @task = Task.find params[:id]
    end

    def update
        @task = Task.find params[:id]
        @task.attributes = params.require(:task).permit(:title, :body, :start_date, :end_date, :status, tag_ids: [])
        @task.save!

        redirect_to task_path(@task)
    rescue ActiveRecord::RecordInvalid
        render action: :new, status: :unprocessable_entity
    end

    def destroy
        @task = Task.find params[:id]
        @task.destroy
        redirect_to tasks_path
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def render_errors(object, method)
        err = object.errors[method]
        unless err.nil?
            err.map{ |e| e.to_s }.join
        end
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TasklistApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <nav>
        <ul>
          <li><%= link_to 'タスク一覧', tasks_path %></li>
          <li><%= link_to 'タスク新規追加', new_task_path %></li>
          <li><%= link_to 'タグ新規追加', new_tag_path %></li>
        </ul>
      </nav>
    </header>
    <main>
      <article>
        <%= yield %>
      </article>

      <aside>
        <h3>ステータス一覧</h3>
        <% Task.statuses.keys.each do |name| %>
          <ul>
              <li><%= link_to name, tasks_path(status: name) %></li>
          </ul>
        <% end %>

        <h3>タグ一覧</h3>
        <% Tag.all.each do |tag| %>
          <ul>
              <li><%= link_to tag.name, tags_path(tag_id: tag.id) %></li>
          </ul>
        <% end %>
      </aside>
    </main>
  </body>
</html>

app/views/tags/edit.html.erb
<%= form_with model: @tag, local: true do |f| %>
    <table>
        <tbody>
            <tr>
                <th>タグ名（必須）</th>
                <td>
                    <%= f.text_field :name %>
                    <%= render_errors f.object, :name %>
                </td>
            </tr>
        </tbody>
    </table>

    <%= f.submit %>
<% end %>

app/views/tags/index.html.erb
<% if @tasks.blank? == false %>
<h2>「<%= @tag_name %>」タグのタスク一覧</h2>
<table>
    <thead>
        <tr>
            <th>タスク名</th>
            <th>開始日</th>
            <th>期日</th>
            <th>ステータス</th>
            <th>編集</th>
            <th>削除</th>
        </tr>
    </thead>
    <tbody>
        <% @tasks.each do |task| %>
        <tr>
            <td><%= link_to task.title, task_path(task) %></td>
            <td><%= task.start_date %></td>
            <td><%= task.end_date %></td>
            <td><%= task.status %></td>
            <td><%= link_to "編集", edit_task_path(task) %></td>
            <td><%= link_to "削除", task_path(task), data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" } %></td>
        </tr>
        <% end %>
    </tbody>
</table>
<% else %>
<h2>「<%= @tag_name %>」タグのタスク一覧</h2>
<p>「<%= @tag_name %>」タグのタスクはありません</p>
<% end %>

app/views/tags/new.html.erb
<h2>新規追加</h2>
<%= form_with model: @tag, local: true do |f| %>
    <table>
        <tbody>
            <tr>
                <th>タグ名（必須）</th>
                <td>
                    <%= f.text_field :name %>
                    <%= render_errors f.object, :name %>
                </td>
            </tr>
        </tbody>
    </table>

    <%= f.submit %>
<% end %>

<% if @tags.blank? == false %>
<h2>タグ一覧</h2>
<table>
    <thead>
        <tr>
            <th>タグ名</th>
            <th>編集</th>
            <th>削除</th>
        <tr>
    </thead>
    <tbody>
        <% @tags.each do |tag| %>
        <tr>
            <td><%= tag.name %></td>
            <td><%= link_to '編集', edit_tag_path(tag) %></td>
            <td><%= link_to '削除', tag_path(tag), data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" } %></td>
        <tr>
        <% end %>
    </tbody>
</table>
<% end %>

app/views/tasks/edit.html.erb
<%= form_with model: @task, local: true do |f| %>
    <table>
        <tbody>
            <tr>
                <th>タスク名（必須）</th>
                <td>
                    <%= f.text_field :title %>
                    <%= render_errors f.object, :title %>
                </td>
            </tr>
            <tr>
                <th>内容</th>
                <td><%= f.text_area :body %></td>
            </tr>
            <tr>
                <th>開始日</th>
                <td><%= f.datetime_local_field  :start_date %></td>
            </tr>
            <tr>
                <th>期日</th>
                <td><%= f.datetime_local_field  :end_date %></td>
            </tr>
            <tr>
                <th>ステータス</th>
                <td><%= f.select :status, Task.statuses.keys %></td>
            </tr>
            <tr>
                <th>タグ</th>
                <td><%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name %></td>
            </tr>
        </tbody>
    </table>

    <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h2>本日締め切りのタスク一覧</h2>
<% if @today_tasks.blank? == false %>
<table>
    <thead>
        <tr>
            <th>タスク名</th>
            <th>開始日</th>
            <th>期日</th>
            <th>ステータス</th>
            <th>編集</th>
            <th>削除</th>
        </tr>
    </thead>
    <tbody>
        <% @today_tasks.each do |task| %>
        <tr>
            <td><%= link_to task.title, task_path(task) %></td>
            <td><%= task.start_date %></td>
            <td><%= task.end_date %></td>
            <td><%= task.status %></td>
            <td><%= link_to "編集", edit_task_path(task) %></td>
            <td><%= link_to "削除", task_path(task), data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" } %></td>
        </tr>
        <% end %>
    </tbody>
</table>
<% else %>
    <p>本日締め切りのタスクはありません</p>
<% end %>

<h2>期限遅れのタスク一覧</h2>
<% if @delay_tasks.blank? == false %>
<table>
    <thead>
        <tr>
            <th>タスク名</th>
            <th>開始日</th>
            <th>期日</th>
            <th>ステータス</th>
            <th>編集</th>
            <th>削除</th>
        </tr>
    </thead>
    <tbody>
        <% @delay_tasks.each do |task| %>
        <tr>
            <td><%= link_to task.title, task_path(task) %></td>
            <td><%= task.start_date %></td>
            <td><%= task.end_date %></td>
            <td><%= task.status %></td>
            <td><%= link_to "編集", edit_task_path(task) %></td>
            <td><%= link_to "削除", task_path(task), data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" } %></td>
        </tr>
        <% end %>
    </tbody>
</table>
<% else %>
    <p>期限切れのタスクはありません</p>
<% end %>

<h2>すべてのタスク一覧</h2>
<% if @tasks.blank? == false %>
<table>
    <thead>
        <tr>
            <th>タスク名</th>
            <th>開始日</th>
            <th>期日</th>
            <th>ステータス</th>
            <th>編集</th>
            <th>削除</th>
        </tr>
    </thead>
    <tbody>
        <% @tasks.each do |task| %>
        <tr>
            <td><%= link_to task.title, task_path(task) %></td>
            <td><%= task.start_date %></td>
            <td><%= task.end_date %></td>
            <td><%= task.status %></td>
            <td><%= link_to "編集", edit_task_path(task) %></td>
            <td><%= link_to "削除", task_path(task), data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" } %></td>
        </tr>
        <% end %>
    </tbody>
</table>
<% else %>
    <p>タスクはありません</p>
<% end %>

app/views/tasks/new.html.erb
<%= form_with model: @task, local: true do |f| %>
    <table>
        <tbody>
            <tr>
                <th>タスク名（必須）</th>
                <td>
                    <%= f.text_field :title %>
                    <%= render_errors f.object, :title %>
                </td>
            </tr>
            <tr>
                <th>内容</th>
                <td><%= f.text_area :body %></td>
            </tr>
            <tr>
                <th>開始日</th>
                <td><%= f.date_field :start_date %></td>
            </tr>
            <tr>
                <th>期日</th>
                <td><%= f.date_field :end_date %></td>
            </tr>
            <tr>
                <th>ステータス</th>
                <td><%= f.select :status, Task.statuses.keys %></td>
            </tr>
            <tr>
                <th>タグ</th>
                <td><%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name %></td>
            </tr>
        </tbody>
    </table>

    <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<dl>
    <dt><b>内容</b></dt>
    <dd><%= @task.body %></dd>

    <dt><b>開始日</b></dt>
    <dd><%= @task.start_date %></dd>

    <dt><b>期日</b></dt>
    <dd><%= @task.end_date %></dd>

    <dt><b>ステータス</b></dt>
    <dd><%= @task.status %></dd>

    <dt><b>タグ</b></dt>
    <dd><%= @task.tags.map(&:name).join(' ') %></dd>
</dl>

<%= link_to '編集', edit_task_path(@task) %>
<%= link_to "削除", task_path(@task), data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" } %>

app/views/tasks/tags.html.erb
<%= link_to '新規作成', new_task_path %>

<% Task.statuses.keys.each do |name| %>
<ul>
    <li><%= link_to name, tasks_path(status: name) %></li>
</ul>
<% end %>

<%= @tag_tasks %>

<h2>すべてのタスク一覧</h2>
<% if @tag_tasks.blank? == false %>
<table>
    <thead>
        <tr>
            <th>タスク名</th>
            <th>開始日</th>
            <th>期日</th>
            <th>ステータス</th>
            <th>編集</th>
            <th>削除</th>
        </tr>
    </thead>
    <tbody>
        <% @tag_tasks.each do |task| %>
        <tr>
            <td><%= link_to task.title, task_path(task) %></td>
            <td><%= task.start_date %></td>
            <td><%= task.end_date %></td>
            <td><%= task.status %></td>
            <td><%= link_to "編集", edit_task_path(task) %></td>
            <td><%= link_to "削除", task_path(task), data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" } %></td>
        </tr>
        <% end %>
    </tbody>
</table>
<% else %>
    <p>タスクはありません</p>
<% end %>